//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSDL_SERVICES.SR1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services/", ConfigurationName="SR1.BanqueService")]
    public interface BanqueService {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/BanqueService/ConversionEuroToDHRequest", ReplyAction="http://services/BanqueService/ConversionEuroToDHResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSDL_SERVICES.SR1.ConversionEuroToDHResponse ConversionEuroToDH(WSDL_SERVICES.SR1.ConversionEuroToDHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/BanqueService/ConversionEuroToDHRequest", ReplyAction="http://services/BanqueService/ConversionEuroToDHResponse")]
        System.Threading.Tasks.Task<WSDL_SERVICES.SR1.ConversionEuroToDHResponse> ConversionEuroToDHAsync(WSDL_SERVICES.SR1.ConversionEuroToDHRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/BanqueService/listComptesRequest", ReplyAction="http://services/BanqueService/listComptesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSDL_SERVICES.SR1.listComptesResponse listComptes(WSDL_SERVICES.SR1.listComptesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/BanqueService/listComptesRequest", ReplyAction="http://services/BanqueService/listComptesResponse")]
        System.Threading.Tasks.Task<WSDL_SERVICES.SR1.listComptesResponse> listComptesAsync(WSDL_SERVICES.SR1.listComptesRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/BanqueService/getCompteRequest", ReplyAction="http://services/BanqueService/getCompteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WSDL_SERVICES.SR1.getCompteResponse getCompte(WSDL_SERVICES.SR1.getCompteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/BanqueService/getCompteRequest", ReplyAction="http://services/BanqueService/getCompteResponse")]
        System.Threading.Tasks.Task<WSDL_SERVICES.SR1.getCompteResponse> getCompteAsync(WSDL_SERVICES.SR1.getCompteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConversionEuroToDH", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class ConversionEuroToDHRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Montant;
        
        public ConversionEuroToDHRequest() {
        }
        
        public ConversionEuroToDHRequest(double Montant) {
            this.Montant = Montant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConversionEuroToDHResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class ConversionEuroToDHResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public ConversionEuroToDHResponse() {
        }
        
        public ConversionEuroToDHResponse(double @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services/")]
    public partial class compte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long codeField;
        
        private bool codeFieldSpecified;
        
        private double soldeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
                this.RaisePropertyChanged("codeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double solde {
            get {
                return this.soldeField;
            }
            set {
                this.soldeField = value;
                this.RaisePropertyChanged("solde");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listComptes", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class listComptesRequest {
        
        public listComptesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listComptesResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class listComptesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSDL_SERVICES.SR1.compte[] @return;
        
        public listComptesResponse() {
        }
        
        public listComptesResponse(WSDL_SERVICES.SR1.compte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCompte", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class getCompteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long code;
        
        public getCompteRequest() {
        }
        
        public getCompteRequest(long code) {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCompteResponse", WrapperNamespace="http://services/", IsWrapped=true)]
    public partial class getCompteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WSDL_SERVICES.SR1.compte @return;
        
        public getCompteResponse() {
        }
        
        public getCompteResponse(WSDL_SERVICES.SR1.compte @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BanqueServiceChannel : WSDL_SERVICES.SR1.BanqueService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BanqueServiceClient : System.ServiceModel.ClientBase<WSDL_SERVICES.SR1.BanqueService>, WSDL_SERVICES.SR1.BanqueService {
        
        public BanqueServiceClient() {
        }
        
        public BanqueServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BanqueServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanqueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanqueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSDL_SERVICES.SR1.ConversionEuroToDHResponse WSDL_SERVICES.SR1.BanqueService.ConversionEuroToDH(WSDL_SERVICES.SR1.ConversionEuroToDHRequest request) {
            return base.Channel.ConversionEuroToDH(request);
        }
        
        public double ConversionEuroToDH(double Montant) {
            WSDL_SERVICES.SR1.ConversionEuroToDHRequest inValue = new WSDL_SERVICES.SR1.ConversionEuroToDHRequest();
            inValue.Montant = Montant;
            WSDL_SERVICES.SR1.ConversionEuroToDHResponse retVal = ((WSDL_SERVICES.SR1.BanqueService)(this)).ConversionEuroToDH(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSDL_SERVICES.SR1.ConversionEuroToDHResponse> WSDL_SERVICES.SR1.BanqueService.ConversionEuroToDHAsync(WSDL_SERVICES.SR1.ConversionEuroToDHRequest request) {
            return base.Channel.ConversionEuroToDHAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSDL_SERVICES.SR1.ConversionEuroToDHResponse> ConversionEuroToDHAsync(double Montant) {
            WSDL_SERVICES.SR1.ConversionEuroToDHRequest inValue = new WSDL_SERVICES.SR1.ConversionEuroToDHRequest();
            inValue.Montant = Montant;
            return ((WSDL_SERVICES.SR1.BanqueService)(this)).ConversionEuroToDHAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSDL_SERVICES.SR1.listComptesResponse WSDL_SERVICES.SR1.BanqueService.listComptes(WSDL_SERVICES.SR1.listComptesRequest request) {
            return base.Channel.listComptes(request);
        }
        
        public WSDL_SERVICES.SR1.compte[] listComptes() {
            WSDL_SERVICES.SR1.listComptesRequest inValue = new WSDL_SERVICES.SR1.listComptesRequest();
            WSDL_SERVICES.SR1.listComptesResponse retVal = ((WSDL_SERVICES.SR1.BanqueService)(this)).listComptes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSDL_SERVICES.SR1.listComptesResponse> WSDL_SERVICES.SR1.BanqueService.listComptesAsync(WSDL_SERVICES.SR1.listComptesRequest request) {
            return base.Channel.listComptesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSDL_SERVICES.SR1.listComptesResponse> listComptesAsync() {
            WSDL_SERVICES.SR1.listComptesRequest inValue = new WSDL_SERVICES.SR1.listComptesRequest();
            return ((WSDL_SERVICES.SR1.BanqueService)(this)).listComptesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSDL_SERVICES.SR1.getCompteResponse WSDL_SERVICES.SR1.BanqueService.getCompte(WSDL_SERVICES.SR1.getCompteRequest request) {
            return base.Channel.getCompte(request);
        }
        
        public WSDL_SERVICES.SR1.compte getCompte(long code) {
            WSDL_SERVICES.SR1.getCompteRequest inValue = new WSDL_SERVICES.SR1.getCompteRequest();
            inValue.code = code;
            WSDL_SERVICES.SR1.getCompteResponse retVal = ((WSDL_SERVICES.SR1.BanqueService)(this)).getCompte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSDL_SERVICES.SR1.getCompteResponse> WSDL_SERVICES.SR1.BanqueService.getCompteAsync(WSDL_SERVICES.SR1.getCompteRequest request) {
            return base.Channel.getCompteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSDL_SERVICES.SR1.getCompteResponse> getCompteAsync(long code) {
            WSDL_SERVICES.SR1.getCompteRequest inValue = new WSDL_SERVICES.SR1.getCompteRequest();
            inValue.code = code;
            return ((WSDL_SERVICES.SR1.BanqueService)(this)).getCompteAsync(inValue);
        }
    }
}
